name: build-python

on:
  push:
    branches: [ "main" ]
    paths:
      - 'python/**'
      - '.github/workflows/build-python.yml'
  workflow_dispatch:

defaults:
  run:
    working-directory: python

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: build-image
      run: docker build . --file Dockerfile --tag  rinoruname/python:${{ env.IMAGE_TAG }}

    - name: docker-login
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PAT }}

    - name: publish-image
      run: |
        docker tag rinoruname/python:${{ env.IMAGE_TAG }} rinoruname/python:latest
        docker push rinoruname/python:${{ env.IMAGE_TAG }}
        docker push rinoruname/python:latest
