name: validate-rule

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build-image
      run: docker build . --file Dockerfile --tag  rinoruname/html:${{ env.IMAGE_TAG }}
      working-directory: html
