name: validate-build-html

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'html/**'
      - '.github/workflows/validate-build-html.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: build-image
      run: docker build . --file Dockerfile --tag  rinoruname/html:latest
      working-directory: html
